name: Build and Package App

on:
  push:
    branches:
      - develop

env:
  NODE_VERSION: 11.x

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Build Frontend
        run: |
          cd client
          npm install
          npm rebuild node-sass
          npm run build

      - name: Build Backend
        run: |
          cd server
          composer update
          composer install

      - name: Package App
        run: |
          cd ..
          echo -n > config.php
          mkdir files2
          cp server/files/.htaccess files2
          mkdir api
          mkdir api/files
          cp server/index.php api
          cp server/.htaccess api
          cp server/composer.json api
          cp server/composer.lock api
          cp -a server/controllers api
          cp -a server/data api
          cp -a server/libs api
          cp -a server/models api
          cp -a server/vendor api
          cp -a files2/. api/files
          rm -rf files2
          cp server/config.php api
          chmod -R 755 .
          cp client/src/index.php client/build
          echo "4/4 Generating zip..."
          cd client/build
          zip opensupports_dev.zip index.php
          zip -u opensupports_dev.zip .htaccess
          zip -u opensupports_dev.zip bundle.js
          zip -ur opensupports_dev.zip images
          mv opensupports_dev.zip ../..
          cd ../..
          zip -ur opensupports_dev.zip api
          mkdir dist
          mv opensupports_dev.zip dist
